// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"Cryptocurrency": {
		"en": "Cryptocurrency",
		"de": "Kryptowährung",
		"ru": "криптовалюта",
		"pt": "Criptomoeda",
		"nl": "cryptogeld",
		"fr": "Crypto-monnaie",
		"it": "criptovaluta",
		"es": "Criptomoneda",
		"pl": "Kryptowaluta"
	},
	"Exchange": {
		"en": "Exchange",
		"de": "Börse",
		"ru": "обмен",
		"pt": "Troca",
		"nl": "Uitwisseling",
		"fr": "Échange",
		"it": "Scambio",
		"es": "Intercambiar",
		"pl": "Wymieniać się"
	},
	"Select Cryptocurrency": {
		"en": "Select Cryptocurrency",
		"de": "Kryptowährung auswählen",
		"ru": "Выберите Cryptocurrency",
		"pt": "Selecione Criptomoeda",
		"nl": "Selecteer Cryptocurrency",
		"fr": "Sélectionnez Crypto-monnaie",
		"it": "Seleziona Criptovaluta",
		"es": "Seleccione Criptomoneda",
		"pl": "Wybierz kryptowalutę"
	},
	"Wallet adress": {
		"en": "Wallet adress",
		"de": "Wallet-Adresse",
		"ru": "Адрес кошелька",
		"pt": "Endereço da carteira",
		"nl": "Wallet-adres",
		"fr": "Adresse du portefeuille",
		"it": "Indirizzo del portafogli",
		"es": "Dirección de billetera",
		"pl": "Adres portfela"
  }
};