// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
	"Cryptocurrency": {
		"en": "Cryptocurrency",
		"de": "Kryptowährung",
		"ru": "криптовалюта",
		"pt": "Criptomoeda",
		"nl": "Cryptogeld",
		"fr": "Crypto-monnaie",
		"it": "Criptovaluta",
		"es": "Criptomoneda",
		"pl": "Kryptowaluta"
	},
	"Exchange": {
		"en": "Exchange",
		"de": "Börse",
		"ru": "обмен",
		"pt": "Troca",
		"nl": "Uitwisseling",
		"fr": "Échange",
		"it": "Scambio",
		"es": "Intercambiar",
		"pl": "Wymieniać się"
	},
	"Select Cryptocurrency": {
		"en": "Select Cryptocurrency",
		"de": "Kryptowährung auswählen",
		"ru": "Выберите Cryptocurrency",
		"pt": "Selecione Criptomoeda",
		"nl": "Selecteer Cryptocurrency",
		"fr": "Sélectionnez Crypto-monnaie",
		"it": "Seleziona Criptovaluta",
		"es": "Seleccione Criptomoneda",
		"pl": "Wybierz kryptowalutę"
	},
	"Wallet adress": {
		"en": "Wallet adress",
		"de": "Wallet-Adresse",
		"ru": "Адрес кошелька",
		"pt": "Endereço da carteira",
		"nl": "Wallet-adres",
		"fr": "Adresse du portefeuille",
		"it": "Indirizzo del portafogli",
		"es": "Dirección de billetera",
		"pl": "Adres portfela"
	},
	"Wallet query on a stock exchange (API key required)": {
		"en": "Wallet query on a stock exchange (API key required)",
		"de": "Wallet Abfrage auf einer Börse (API-Key erdorderlich)",
		"ru": "Запрос кошелька на фондовой бирже (требуется ключ API)",
		"pt": "Consulta de carteira em bolsa de valores (requer chave de API)",
		"nl": "Wallet-query op een beurs (API-sleutel vereist)",
		"fr": "Requête Google Wallet sur une bourse (clé API requise)",
		"it": "Query Wallet su una borsa (è richiesta una chiave API)",
		"es": "Consulta de cartera en una bolsa (se requiere clave de API)",
		"pl": "Kwerenda portfela na giełdzie (wymagany klucz API)"
	}
};